### ISSUE TITLE
Kmod_External DeadlySignal

### ISSUE THREAD

**Issue by WizardMan1337** [Heep042/vmread#10]
im trying to use your Kmod_example but everytime i try i get this

`sudo ./kmod_example
Using Mode: MODE_EXTERNAL
Mapping VM memory, this will take a second...
Mem:	7efb75200000	| Size:	6d6000000
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7296==ERROR: AddressSanitizer: SEGV on unknown address 0x7efb75200000 (pc 0x7f3c1c5a76c4 bp 0x7fff9f6b3c90 sp 0x7fff9f6b3418 T0)
==7296==The signal is caused by a READ memory access.
    #0 0x7f3c1c5a76c3  (/lib/x86_64-linux-gnu/libc.so.6+0xbb6c3)
    #1 0x4dc41d  (/home/alec/ree/vmread/build/kmod_example+0x4dc41d)
    #2 0x52f5db  (/home/alec/ree/vmread/build/kmod_example+0x52f5db)
    #3 0x51db67  (/home/alec/ree/vmread/build/kmod_example+0x51db67)
    #4 0x51cc2d  (/home/alec/ree/vmread/build/kmod_example+0x51cc2d)
    #5 0x52c7d9  (/home/alec/ree/vmread/build/kmod_example+0x52c7d9)
    #6 0x52a0fc  (/home/alec/ree/vmread/build/kmod_example+0x52a0fc)
    #7 0x53531c  (/home/alec/ree/vmread/build/kmod_example+0x53531c)
    #8 0x7f3c1c50db27  (/lib/x86_64-linux-gnu/libc.so.6+0x21b27)
    #9 0x41daf9  (/home/alec/ree/vmread/build/kmod_example+0x41daf9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0xbb6c3) 
==7296==ABORTING
`

i have tried changing the compiler to clang different versions of clang and different versions of gcc and g++ but to no avail. I know 2 other people who are having the same issue.

**Comment by h33p** [comment]
Seems like you have not loaded in the vmread kernel module. Be sure to check dmesg for this line:

```
vmread: initialized
```

When it is loaded in properly and the example code runs, you should see something like this in the dmesg output:

```
[ 2764.049071] vmread: checking 0x400000 pages
[ 2764.104599] vmread: got 0x400000 pages
[ 2764.563695] vmread: mapping successful!
```

If any of this fails, please post the errors and the stacktrace when built in debug mode (meson's --buildtype=debug option).

**Comment by WizardMan1337** [comment]
thanks i figured it out
