### ISSUE TITLE
Host and Guest crash

### ISSUE THREAD

**Issue by ahmetabdi** [Heep042/vmread#14]
Thanks for the library it is working very well.

I'm trying to run the example injection method to get faster READ&WRITE operations because currently in external mode its not fast enough for what I need it for so I'm testing the example in this project but where I run the injection script `sudo ./inject` everything crashes and I have cycle the power.

Win is 1903, is there some alternative method for reading faster or what could possibly be the cause of the crash using the example?

**Comment by h33p** [comment]
The crash probably occurs due to permission issues. A much safer method is to use the kernel module to remap the memory of VM. Please read README for more information

**Comment by ahmetabdi** [comment]
Thanks much better :+1:
