### ISSUE TITLE
Infinite loop regression.

### ISSUE THREAD

**Issue by vldr** [Heep042/vmread#21]
Hi,

I've encountered a strange infinite loop regression when finding module information for the "svchost.exe" process. (Guest: Windows 10 1909)

I've pinned it down to this section of code. FillModuleInfo64 sets the head to 0x0 and an infinite loop occurs.
https://github.com/Heep042/vmread/blob/master/wintools.c#L677

A temporary "fix" would be to limit the number iterations if the head becomes null.

Thanks.

**Comment by h33p** [comment]
prev was supposed to be used to tackle this particular issue, but it appears to be unused. I will push a fix soon.

**Comment by h33p** [comment]
Should be fixed in https://github.com/Heep042/vmread/commit/49a0027fa79ed9c2dd9768c054e09481cbc3ee45 thanks for reporting
