### ISSUE TITLE
what's MODE_DMA for?

### ISSUE THREAD

**Issue by oovz** [Heep042/vmread#22]
What's MODE_DMA for? I'm not seeing it used in anywhere besides line#127 in wintools.c

**Comment by h33p** [comment]
It was meant for supporting hardware based methods of reading memory (primarily ignoring KFIX values, since those would be irrelevant in DMA), but so far no such support is built-in, thus this mode remains unused, apart from that particular check to ignore re-running with modified KFIX value.
