### ISSUE TITLE
Not an actual issue.

### ISSUE THREAD

**Issue by unfriendly** [Heep042/vmread#24]
Hi, I am learning and I am wondering if you would have any time to talk about your vmread library and kernel module.

**Comment by h33p** [comment]
Sure, go ahead

**Comment by unfriendly** [comment]
Do you have a Discord or other chat software like wire, threema, etc...? (My email is publicly listed on my github profile, if you want to send it over non public channels)

**Comment by h33p** [comment]
Add me on Discord Heep#3574
