### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by illion20** [Heep042/vmread#3]
I am new to meson and ninja, this is what I have installed:
- Ubuntu 18.04 LTS
- gcc 7.3.0
- meson 0.50.0
- ninja 1.8.2

I clone this repo and I ran meson build and then ninja.
First thing I noticed was that your default_option seems to be off:
`default_options : ['c_std=c99', 'c++_std=c++11']`
shouldn't it be?
`'cpp_std=c++11'`

Then I fail building due to:
`//'-Wno-old-style-cast', '-Wno-missing-prototypes', '-Weverything'`
`cc1: error: command line option ‘-Wno-old-style-cast’ is valid for C++/ObjC++ but not for C [-Werror]`

Removing the above I hit errors like this:
`../wintools.c:25: undefined reference to `pmparser_parse'`

Solved it by adding pmparser.c:
`base_files = ['mem.c', 'wintools.c', 'pmparser.c']`

So just curious what is going on?

**Comment by h33p** [comment]
It was my mistake. Did not update the example build file to include pmparser.c

Regarding the warning arguments, GCC does not have many of them.

All of this should be fixed in https://github.com/Heep042/vmread/commit/293af14db4abfa3879021e8e87bbf4fdd80a37f7
