### ISSUE TITLE
Linux 5.8 changes

### ISSUE THREAD

**Issue by ntegan** [Heep042/vmread#35]
Archlinux,  
`uname -r` == `5.8.5-arch1-1`,  
had to modify kmem.c a bit to compile.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9740ca4e95b43b91a4a848694a20d01ba6818f7b  
Had to use this instead of trying to access `mm->mmap_sem`.

Had to `#include <linux/vmalloc.h>`

**Comment by h33p** [comment]
Including vmalloc may be needed. But I wouldn't be sure about adding specific code paths for the locking wrappers anymore. This repo is going to be deprecated very soon, and having 5.8 kernel latest support should be a good ending point. Thank you for pointing this out.

**Comment by h33p** [comment]
On the contrary, mmap_sem is not accessible on 5.8, it would need a separate code path just to support 5.8. Thus, I am choosing not to update it for vmread, it will be, however, updated in [memflow-kvm](https://github.com/memflow/memflow-kvm)
