### ISSUE TITLE
Process disappears from list sometimes

### ISSUE THREAD

**Issue by fatalis** [Heep042/vmread#4]
Sometimes the process disappears from the list until I restart the game. When this happens it also doesn't show up in kvm_explorer.  No idea why this is happening, not much happens between when It was working fine and then suddenly disappears. I notice it after restarting my hack a lot when coding.

Also, any plans to add memory page enumeration? I forked cheat engine's ceserver and made it use vmread and I can use CE browse memory, but page enum is needed to scan and low level windows is way over my head and I don't think I can do it myself.

Thanks for the cool lib :)

EDIT: For whatever reason, opening task manager fixes it. Decent enough workaround I guess

**Comment by seeker25** [comment]
I might be really stupid saying this, but I think there is a huge page mode?

https://help.ubuntu.com/community/KVM%20-%20Using%20Hugepages

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_tuning_and_optimization_guide/sect-virtualization_tuning_optimization_guide-memory-tuning

Sorry if i'm wrong.

**Comment by fatalis** [comment]
Yeah, I'm using 1GB hugepages, guess that's why this is happening for me? Keeping task manager open all the time is a good enough fix for me though.

**Comment by h33p** [comment]
I don't think it has anything to do with hugepages. It could be something changed about the process state in recent windows updates that task monitoring corrects, but I have been out of the loop for a better part of 3 months so I can not say for sure. If the task manager fixes it, let it be a workaround until I get back from my break. If anyone is interested in experimenting, [this](https://github.com/Heep042/vmread/blob/293af14db4abfa3879021e8e87bbf4fdd80a37f7/wintools.c#L252) part would be of great interest.

Not closing until a proper solution is found.

**Comment by fatalis** [comment]
Did some logging and yeah, `session` is going to 0 when this occurs. 1809 btw

**Comment by h33p** [comment]
Should be fixed in https://github.com/Heep042/vmread/commit/9c4314e6774cb0ea650e007ed7eee12bdf57774a
